In [2]:
import numpy as np

# Initialising a Numpy array and Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# get the dimension
print(a.ndim)

1


In [5]:
# shape of array
print(a.shape)

(3,)


In [6]:
# get type
print(a.dtype)

int32


In [7]:
# get total size
print(a.size)

3


In [8]:
#get the no of byte
print(a.nbytes)

12


# Accessing Elements

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r, c]
a[1, 5]

13

In [11]:
# Get a specific row 
a[1, :]


array([ 8,  9, 10, 11, 12, 13, 14])

In [12]:
# Get a specific column
a[:, 5]

array([ 6, 13])

# Changing elements

In [13]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [14]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# Initialising different types of array

In [19]:
# All 0s matrix
np.zeros((2,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
# All 1s matrix
np.ones((2,2), dtype='int32')

array([[1, 1],
       [1, 1]])

In [22]:
# Any other number
np.full((2,2), 100,dtype='int32')

array([[100, 100],
       [100, 100]])

In [23]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.669307  , 0.71615342],
       [0.019976  , 0.69433315],
       [0.81794488, 0.82735244],
       [0.10699572, 0.39633461]])

In [24]:
# Random Integer values
np.random.randint(1,8, size=(3,3))

array([[3, 1, 7],
       [2, 5, 1],
       [5, 7, 3]])

In [27]:
# The identity matrix
np.identity(3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Mathematics 

In [35]:
a = np.array([1,2,3,4])

In [36]:
a= a+2
print(a)

[3 4 5 6]


In [37]:
a = a - 2
print(a)

[1 2 3 4]


In [38]:
a = a * 4
print(a)

[ 4  8 12 16]


# Linear algebra

In [39]:
# Matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

# Statistics

In [41]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats)

1

In [43]:
np.max(stats)

6

In [44]:
np.sum(stats)

21